services:
  app:
    build:
      context: .. # Build context points to the parent directory
      dockerfile: docker/Dockerfile
      args:
        ENV: prod # Use production requirements
    ports:
      - "8000:8000" # Expose FastAPI app
    env_file:
      - ./.env
    environment:
      - UVICORN_ENV=PRODUCTION
      - LOG_LEVEL=INFO
      - LOG_PATH=logs/app.log
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    restart: always